### ISSUE TITLE
Dubbed Downloads

### ISSUE THREAD

**Issue by ghero101** [turtletowerz/crunchyrip#1]
![Capture](https://user-images.githubusercontent.com/58798443/70755616-528ae680-1d08-11ea-95d0-3d70f325608d.PNG)
I am not sure if this is an issues with crunchyroll or an issue with the ripper. I was attempting to grab a series with english dub or subs. I was having trouble gathering either. It would also be nice if there was a qay to set up the command to select the language of the episode and not just of the subtitle(unless I missed it). for reference I was running  "crunchyrip -s none -q 360 username password https://www.crunchyroll.com/rurouni-kenshin"

I found that without specifying -s none I got an error that it couldnt get a subtitle match
[crunchyrip] Error getting episode info: could not find stream with language "enUS"

once I addressed that with -s none, i got the following error:
[crunchyrip] Error downloading episode: getting best stream url: no stream of quality "360"

this was regardless of the -q I tried (1080, 720, 480, 360)

Appreciate any ideas or support you can give

Thank you

**Comment by turtletowerz** [comment]
This seems to be a bit of a bizarre case. The show is old enough that the hardcoded subtitles are actually not crunchyroll's, meaning they display the subtitle language as `""`. You were on the right track by setting the -subs flag to `none`. 

As for the second error, that appears to be due to the unusual resolutions of the show. The highest resolution there is for this series is `620x480`. The closest default resolution is `848x480`.

In order to fix these, I will work on adding support for dubbed seasons. The new `-dub` argument will automatically remove subtitles which will fix the first error. I also plan on adding a custom resolution flag where you can set `-res 620x480` and it will download that specific resolution.

Thank you for pointing out some of these issues. Since I don't watch much older content I would've never found this.

**Comment by ghero101** [comment]
Thank you for finding it and looking into it. I'm just glad I wasn't missing something obvious. I do appreciate the work you are doing on this, and if I was more familiar with go, I would have looked further into a solution. Thank you again, I tried several other similar projects and none of them have worked as well as this.

**Comment by turtletowerz** [comment]
I just pushed an update that added `-dub` and `-res`, which should hopefully fix this issue. In order to download the show now, you have two options:

`crunchyrip -s none -q 624x480 username password https://www.crunchyroll.com/rurouni-kenshin`
Will download the version with Japanese audio and no subtitles

`crunchyrip -dub -q 624x480 username password https://www.crunchyroll.com/rurouni-kenshin`
Will download the version with English audio and no subtitles

Please test this for me so I can be sure that the new fixes work

**Comment by ghero101** [comment]
I was able to download the files, atleast the first few so far. Looks like its working just fine, I'll test it with some other english dubs later on and let you know if I have any further issues. Again outstanding work, and phenomenal response times.

**Comment by turtletowerz** [comment]
You just caught me on a good day 😄 

I'll close this, so please open a new one if more random errors come up
