### ISSUE TITLE
Quality Downloads

### ISSUE THREAD

**Issue by ghero101** [turtletowerz/crunchyrip#2]
I have found that various anime change resolutions throughout the series what this causes when downloading entire shows, (yes older ones). It will rip everything in the available resolution but after it changes it will stop downloading files because there is no resolution match. Since you are able to return a list of available resolutions, would it be possible to do a few things. 1 is give a max parameter, so that the ripper will grab the greatest quality file that is available, or if we specify 1080, but only 720 is available it will drop to 720 for the episodes where 1080 is not available.

Otherwise what I have had to do it run the cmd several times until I get all the episodes. fortunately you check if the files exist so this is not a major issue, more of an inconvenience. 

Thank you again for all you support

**Comment by turtletowerz** [comment]
I think adding a `max` and `min` is an interesting idea, but I don't want to drop to 720p if 1080p isn't available. The user has to specify they want 1080p, so dropping them to 720p wouldn't make sense because it isn't what they wanted. I'll work on adding `min/max`, but it may take a few days as I am fairly busy at the moment

Thanks for the suggestions!

**Comment by turtletowerz** [comment]
Okay, I've added the `min` and `max` flag values for quality, as well as a new flag called `options`. This will only print the available qualities, and not actually download anything

Note that this may be extremely buggy as it was a pain in the ass to implement so I didn't thoroughly test on multiple shows. I tested on the show from your first issue and it seemed to work fine.
